name:                love-letter
version:             0.1.0.0
github:              "githubuser/love-letter"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/love-letter#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- microlens
- microlens-th
- vty
- vector
- containers
- random
- array

default-extensions:
- RecordWildCards
- TemplateHaskell

library:
  source-dirs: src

executables:
  love-letter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - love-letter

# tests:
#   love-letter-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - love-letter
